import React from 'react';
import type { Metadata } from 'next';
import './globals.css';
import Navigation from '@/components/Navigation/Navigation';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html className="h-full bg-gray-100" lang="en">
            <body className="h-full">
                <div className="min-h-full">
                    <Navigation />
                    <header className="bg-white shadow">
                        <div className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
                            <h1 className="text-3xl font-bold tracking-tight text-gray-900">
                                Karim Shehadeh
                            </h1>
                        </div>
                    </header>
                    <main>
                        <div className="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
                            {children}
                        </div>
                    </main>
                </div>
            </body>
        </html>
    );
}
